### PR TITLE
Task count trigger

### LINKED ISSUE #15: Implement Trigger TaskCount
on active resources.

### PR DESCRIPTION
**Pull request by kjuli**
This PR implements the TaskCount trigger for active resources by using the STATE_OF_ACTIVE_RESOURCE measuring point.

Here, some functionality that originally belonged to `CPUUtilizationTriggerChecker` where abstracted into a `AbstractManagedElementTriggerChecker` class, since the new `TaskCountTriggerChecker` shares many of them with the CPU trigger checker, and probably other `ManagedElementTrigger`s are going to behave the same way.

When approved, this PR will close #15 .

### CODE REVIEW

**Comment by stiesssh** [comment]
currently, you check the target group twice, once in the `TargetGroupChecker` and once in `isMeasuringPointInTargetGroup` in `TaskCountTriggerChecker`.i'd assume, they check different aspects of the TargetGroups, but it's unclear to me what the differences are. Thus, could you add some documentation, about which check checks for what?

**Review by stiesssh — COMMENTED** [review]
checked for all aggragation types, and it works! 
get me that bit of additional documentation i requested in the comment above, and you i'm happy : D

**Comment by kjuli** [comment]
That is true, this is an actual oversight :D I am looking currently what approach is better, and will delete one of those methods instead.

**Review by stiesssh — CHANGES_REQUESTED** [review]
huh, i like that switch-base approach :0
looks like something that's clean and easy to extend for other MPs.

**Review by stiesssh — APPROVED** [review]
lgtbm :P

**Pull request merged**
